# Catppuccin Mocha theme
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[cursor]
style = "Block"
unfocused_hollow = true

# Improve terminal response
[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"  # Enable true color support
EDITOR = "nvim"  # Set default editor

[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

# Better font rendering
[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

# Disable built-in font scaling
builtin_box_drawing = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" }
]

# Creates a new tmux window (CMD + t)
# Similar to opening a new tab in Terminal.app
[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

# Opens tmux preferences (CMD + ,)
# Similar to opening preferences in macOS apps
[[keyboard.bindings]]
chars = "\u0001,"
key = "Comma"
mods = "Command"

# Quick window/tab switching using CMD + number
# Similar to Chrome/Safari tab switching
[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"
# Switch to tmux window 1

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"
# Switch to tmux window 2

[[keyboard.bindings]]
chars = "\u00013"
key = "Key3"
mods = "Command"
# Switch to tmux window 3

[[keyboard.bindings]]
chars = "\u00014"
key = "Key4"
mods = "Command"
# Switch to tmux window 4

[[keyboard.bindings]]
chars = "\u00015"
key = "Key5"
mods = "Command"
# Switch to tmux window 5

[[keyboard.bindings]]
chars = "\u00016"
key = "Key6"
mods = "Command"
# Switch to tmux window 6

[[keyboard.bindings]]
chars = "\u00017"
key = "Key7"
mods = "Command"
# Switch to tmux window 7

[[keyboard.bindings]]
chars = "\u00018"
key = "Key8"
mods = "Command"
# Switch to tmux window 8

[[keyboard.bindings]]
chars = "\u00019"
key = "Key9"
mods = "Command"
# Switch to tmux window 9

# Split current pane horizontally (CMD + Shift + D)
# Creates a new pane below the current one
[[keyboard.bindings]]
chars = "\u0001\""
key = "D"
mods = "Command|Shift"

# Split current pane vertically (CMD + D)
# Creates a new pane to the right of the current one
[[keyboard.bindings]]
chars = "\u0001%"
key = "D"
mods = "Command"

# Save in vim/neovim (CMD + S)
# Sends Escape :w Enter sequence
[[keyboard.bindings]]
chars = "\u001B:w\r"
key = "S"
mods = "Command"

# Close current window/tab (CMD + W)
# Similar to closing tabs in other macOS apps
[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

# Move cursor forward one word (Alt + Right)
# Similar to macOS text navigation
[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

# Move cursor backward one word (Alt + Left)
# Similar to macOS text navigation
[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

# Copy selected text (CMD + C)
# Uses system clipboard
[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

# Paste text (CMD + V)
# Pastes from system clipboard
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

# Switch to previous tab (CMD + Left)
# Similar to tab navigation in Safari/Chrome
[[keyboard.bindings]]
chars = "\u0001["
key = "Left"
mods = "Command"

# Switch to next tab (CMD + Right)
# Similar to tab navigation in Safari/Chrome
[[keyboard.bindings]]
chars = "\u0001]"
key = "Right"
mods = "Command"

# Undo last action (CMD + Z)
# Standard macOS undo shortcut
[[keyboard.bindings]]
chars = "\u0001z"
key = "Z"
mods = "Command"

# Find/Search (CMD + F)
# Standard macOS find shortcut
[[keyboard.bindings]]
chars = "\u0001f"
key = "F"
mods = "Command"

# Create new window (CMD + N)
# Similar to new window in Terminal.app
[[keyboard.bindings]]
chars = "\u0001n"
key = "N"
mods = "Command"

# Quit application (CMD + Q)
# Standard macOS quit shortcut
[[keyboard.bindings]]
chars = "\u0001q"
key = "Q"
mods = "Command"

# Scroll up in terminal (CMD + Up)
# Similar to page up
[[keyboard.bindings]]
chars = "\u001B[A"
key = "Up"
mods = "Command"

# Scroll down in terminal (CMD + Down)
# Similar to page down
[[keyboard.bindings]]
chars = "\u001B[B"
key = "Down"
mods = "Command"

# Reopen last closed tab (CMD + Shift + T)
# Similar to browser behavior
[[keyboard.bindings]]
chars = "\u0001T"
key = "T"
mods = "Command|Shift"

# Increase font size (CMD + Plus)
# Standard zoom in shortcut
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

# Decrease font size (CMD + Minus)
# Standard zoom out shortcut
[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

# Reset font size to default (CMD + 0)
# Standard zoom reset shortcut
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[scrolling]
history = 50000  # Increased from 10000
multiplier = 3
auto_scroll = true  # Enable auto-scroll

[selection]
save_to_clipboard = true  # Automatically copy selection to clipboard
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"  # Better word selection

[terminal]
# Better performance settings
osc52 = "CopyPaste"  # Enable OSC52 copying
working_directory = "None"  # Auto-detect working directory

[terminal.shell]
args = ["--login", "-c", "tmux new-session"]  # Named session
program = "/bin/zsh"

[window]
decorations = "buttonless"  # More native macOS look
opacity = 1.0
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"
option_as_alt = "Both"  # Better Alt key handling

# Improve window dimensions
[window.dimensions]
columns = 120  # Better default width
lines = 30    # Better default height

# Better padding for Neovim
[window.padding]
x = 8
y = 8

[debug]
# Improve performance
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

# GPU acceleration
[gpu]
vsync = true
