[cursor]
blink_interval = 750
blink_timeout = 5
thickness = 0.15
vi_mode_style = "Block"
unfocused_hollow = true

# Improve terminal response
[env]
TERM = "alacritty"
COLORTERM = "truecolor"  # Enable true color support
EDITOR = "nvim"  # Set default editor

[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

# Better font rendering
[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
  { mouse = "Right", action = "ExpandSelection" }
]

# Creates a new tmux window (CMD + t)
# Similar to opening a new tab in Terminal.app
[[keyboard.bindings]]
chars = "\u0001c"
key = "T"
mods = "Command"

# Split current pane horizontally (CMD + Shift + D)
# Creates a new pane below the current one
[[keyboard.bindings]]
chars = "\u0001\""
key = "D"
mods = "Command|Shift"

# Split current pane vertically (CMD + D)
# Creates a new pane to the right of the current one
[[keyboard.bindings]]
chars = "\u0001%"
key = "D"
mods = "Command"

# Close current window/tab (CMD + W)
# Similar to closing tabs in other macOS apps
[[keyboard.bindings]]
chars = "\u0001x"
key = "W"
mods = "Command"

# Create new window (CMD + N)
# Similar to new window in Terminal.app
[[keyboard.bindings]]
chars = "\u0001n"
key = "N"
mods = "Command"

# Increase font size (CMD + Plus)
# Standard zoom in shortcut
[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

# Decrease font size (CMD + Minus)
# Standard zoom out shortcut
[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

# Reset font size to default (CMD + 0)
# Standard zoom reset shortcut
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

# Navigate between windows (Cmd + 1-9)
[[keyboard.bindings]]
chars = "\u00011"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00012"
key = "Key2"
mods = "Command"

# Close window (Cmd + W)
[[keyboard.bindings]]
chars = "\u0001&"
key = "W"
mods = "Command"

[scrolling]
history = 100000 # Increased from 10000
multiplier = 5 # Faster scrolling

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"
args = [
  "--login",
  "-c",
  "tmux new-session -A -s main"
]

[window]
dynamic_title = true
padding = { x = 10, y = 10 }
option_as_alt = "Both"

# Improve window dimensions
[window.dimensions]
columns = 120  # Better default width
lines = 30    # Better default height

[general]
live_config_reload = true
import = [
  "~/.catppuccin.toml"
]

