# GNU utilities
brew "coreutils"
brew "moreutils"
brew "findutils"
brew "gnu-sed"
brew "bash"
brew "bash-completion@2"
brew "gnupg"

# CLI tools
brew "lsd"
brew "fd"
brew "fzf"
brew "git"
brew "mas"
brew "ripgrep"
brew "tealdeer"
brew "lazygit"
brew "neovim"
brew "tmux"
brew "z"
brew "asdf"
brew "chezmoi"
brew "stylua"
brew "gh"
brew "jq"
brew "shellcheck"
brew "tree"
brew "hyperfine"
brew "tig"
brew "pandoc"

# Container runtime
brew "colima"
brew "docker"
brew "docker-compose"
brew "docker-buildx"
brew "docker-credential-helper-ecr"

# Zsh plugins
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh-completions"

# Fonts
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# GUI applications
cask "1password"
cask "betterdisplay"
cask "deepl"
cask "figma"
cask "ghostty"
cask "google-chrome"
cask "hiddenbar"
cask "imageoptim"
cask "obsidian"
cask "postman"
cask "raycast"
cask "shottr"
cask "slack"
cask "spotify"
cask "todoist-app"
cask "visual-studio-code"

# Mac App Store
mas "The Unarchiver", id: 425424353
mas "Amphetamine", id: 937984704
mas "Be Focused Pro", id: 961632517
mas "Presentify", id: 1507246666

# VSCode extensions
vscode "anthropic.claude-code"
vscode "bierner.markdown-mermaid"
vscode "catppuccin.catppuccin-vsc"
vscode "christian-kohler.npm-intellisense"
vscode "codeandstuff.package-json-upgrade"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "donjayamanne.githistory"
vscode "dracula-theme.theme-dracula"
vscode "dsznajder.es7-react-js-snippets"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "hashicorp.terraform"
vscode "mattpocock.ts-error-translator"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.vscode-speech"
vscode "ms-vsliveshare.vsliveshare"
vscode "redhat.vscode-yaml"
vscode "scala-lang.scala"
vscode "sdras.night-owl"
vscode "stylelint.vscode-stylelint"
vscode "tomoyukim.vscode-mermaid-editor"
vscode "unifiedjs.vscode-mdx"
vscode "vayan.haml"
vscode "vitest.explorer"
vscode "vscodevim.vim"
vscode "waderyan.gitblame"
vscode "wayou.vscode-todo-highlight"
vscode "xabikos.javascriptsnippets"
vscode "yoavbls.pretty-ts-errors"
